In [1]:
import pandas as pd, numpy as np, datetime as dt

In [2]:
billy_df = pd.read_csv("billboardHot100_1999-2019.csv")

In [3]:
billy_df.head()

,Unnamed: 0,Artists,Name,Weekly.rank,Peak.position,Weeks.on.chart,Week,Date,Genre,Writing.Credits,Lyrics,Features
0,1,"Lil Nas,",Old Town Road,1,1.0,7.0,2019-07-06,"April 5, 2019","Country,Atlanta,Alternative Country,Hip-Hop,Tr...","Jozzy, Atticus ross, Trent reznor, Billy ray c...","Old Town Road Remix \nOh, oh-oh\nOh\nYeah, I'm...",Billy Ray Cyrus
1,2,"Shawn Mendes, Camila Cabello",Senorita,2,NaN,NaN,2019-07-06,"June 21, 2019",Pop,"Cashmere cat, Jack patterson, Charli xcx, Benn...",Senorita \nI love it when you call me senorita...,NaN
2,3,Billie Eilish,Bad Guy,3,2.0,13.0,2019-07-06,"March 29, 2019","Hip-Hop,Dark Pop,House,Trap,Memes,Alternative ...","Billie eilish, Finneas","bad guy \nWhite shirt now red, my bloody nose\...",NaN
3,4,Khalid,Talk,4,3.0,20.0,2019-07-06,"February 7, 2019","Synth-Pop,Pop","Howard lawrence, Guy lawrence, Khalid",Talk \nCan we just talk? Can we just talk?\nTa...,NaN
4,5,"Ed Sheeran, Justin Bieber",I Don't Care,5,2.0,7.0,2019-07-06,"May 10, 2019","Canada,UK,Dance,Dance-Pop,Pop","Ed sheeran, Justin bieber, Shellback, Max mart...",I Don't Care \nI'm at a party I don't wanna be...,NaN

In [4]:
billy_df.drop(["Unnamed: 0", "Date", "Writing.Credits", "Lyrics", "Features"], axis=1, inplace=True)

In [5]:
billy_df.to_csv("billboard_revised.csv")

In [5]:
billy_df.head()

,Artists,Name,Weekly.rank,Peak.position,Weeks.on.chart,Week,Genre
0,"Lil Nas,",Old Town Road,1,1.0,7.0,2019-07-06,"Country,Atlanta,Alternative Country,Hip-Hop,Tr..."
1,"Shawn Mendes, Camila Cabello",Senorita,2,NaN,NaN,2019-07-06,Pop
2,Billie Eilish,Bad Guy,3,2.0,13.0,2019-07-06,"Hip-Hop,Dark Pop,House,Trap,Memes,Alternative ..."
3,Khalid,Talk,4,3.0,20.0,2019-07-06,"Synth-Pop,Pop"
4,"Ed Sheeran, Justin Bieber",I Don't Care,5,2.0,7.0,2019-07-06,"Canada,UK,Dance,Dance-Pop,Pop"

In [6]:
billy_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 97225 entries, 0 to 97224
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Artists         97225 non-null  object
 1   Name            97225 non-null  object
 2   Weekly.rank     97225 non-null  int64
 3   Peak.position   90156 non-null  float64
 4   Weeks.on.chart  90156 non-null  float64
 5   Week            97225 non-null  object
 6   Genre           97225 non-null  object
dtypes: float64(2), int64(1), object(4)
memory usage: 5.2+ MB

In [7]:
for index, row in billy_df.iterrows():
    date_str = row["Week"]
    revised_date = dt.datetime.strptime(date_str, "%Y-%m-%d")
    week_date = dt.datetime.strftime(revised_date, "%Y-%W") 
    week_date = str(week_date).split("-")
    year = int(week_date[0])
    week = int(week_date[1])
    week /= 52
    decimal_date = year + week
    billy_df.loc[index, "DecDate"] = decimal_date

In [8]:
sorted_df = billy_df.sort_values(["Artists", "Name"])#.assign(last_value=lambda x: x.)

In [9]:
sorted_df2 = sorted_df.set_index(["Artists", "Name", "Week"])

In [10]:
sorted_df2.head()

                                               Weekly.rank  Peak.position  \
Artists             Name           Week
"Weird Al" Yankovic Canadian Idiot 2006-11-01           98           82.0
                                   2006-10-25           94           82.0
                                   2006-10-18           82            NaN
                    Word Crimes    2014-08-08           91           39.0
                                   2014-08-01           39            NaN

                                               Weeks.on.chart  \
Artists             Name           Week
"Weird Al" Yankovic Canadian Idiot 2006-11-01             3.0
                                   2006-10-25             2.0
                                   2006-10-18             NaN
                    Word Crimes    2014-08-08             2.0
                                   2014-08-01             NaN

                                                            Genre      DecDate
Artists             Name           Week
"Weird Al" Yankovic Canadian Idiot 2006-11-01  Comedy,Parody,Rock  2006.846154
                                   2006-10-25  Comedy,Parody,Rock  2006.826923
                                   2006-10-18  Comedy,Parody,Rock  2006.807692
                    Word Crimes    2014-08-08   Parody,Comedy,Pop  2014.596154
                                   2014-08-01   Parody,Comedy,Pop  2014.576923

In [12]:
jj = 2
for i, r in sorted_df2.iterrows():
    if jj == 2:
        print(i[0])
        jj += 1
        #     if np.isnan(r["Peak.position"]):
#         sorted_df.loc[i, "Peak.position"] = r["Weekly.rank"]
#     if np.isnan(r["Weeks.on.chart"]):
#         sorted_df.loc[i, "Weeks.on.chart"] = 1.0

"Weird Al" Yankovic

In [11]:
np.isnan(sorted_df.iloc[2, :]["Peak.position"])

True

In [12]:
np.isnan(3)

False

In [13]:
b_df2 = billy_df.copy(deep=True)

In [14]:
b_df2.head()

,Artists,Name,Weekly.rank,Peak.position,Weeks.on.chart,Week,Genre,DecDate
0,"Lil Nas,",Old Town Road,1,1.0,7.0,2019-07-06,"Country,Atlanta,Alternative Country,Hip-Hop,Tr...",2019.5
1,"Shawn Mendes, Camila Cabello",Senorita,2,NaN,NaN,2019-07-06,Pop,2019.5
2,Billie Eilish,Bad Guy,3,2.0,13.0,2019-07-06,"Hip-Hop,Dark Pop,House,Trap,Memes,Alternative ...",2019.5
3,Khalid,Talk,4,3.0,20.0,2019-07-06,"Synth-Pop,Pop",2019.5
4,"Ed Sheeran, Justin Bieber",I Don't Care,5,2.0,7.0,2019-07-06,"Canada,UK,Dance,Dance-Pop,Pop",2019.5

In [15]:
for i, r in b_df2.iterrows():
    if np.isnan(r["Peak.position"]):
        b_df2.loc[i, "Peak.position"] = r["Weekly.rank"]
        b_df2.loc[i, "Weeks.on.chart"] = 1.0

In [16]:
b_df2.head()

,Artists,Name,Weekly.rank,Peak.position,Weeks.on.chart,Week,Genre,DecDate
0,"Lil Nas,",Old Town Road,1,1.0,7.0,2019-07-06,"Country,Atlanta,Alternative Country,Hip-Hop,Tr...",2019.5
1,"Shawn Mendes, Camila Cabello",Senorita,2,2.0,1.0,2019-07-06,Pop,2019.5
2,Billie Eilish,Bad Guy,3,2.0,13.0,2019-07-06,"Hip-Hop,Dark Pop,House,Trap,Memes,Alternative ...",2019.5
3,Khalid,Talk,4,3.0,20.0,2019-07-06,"Synth-Pop,Pop",2019.5
4,"Ed Sheeran, Justin Bieber",I Don't Care,5,2.0,7.0,2019-07-06,"Canada,UK,Dance,Dance-Pop,Pop",2019.5

In [17]:
sorted_df2 = b_df2.sort_values(["Artists", "Name", "Week"]).set_index(["Artists", "Name", "Week"])

In [18]:
sorted_df2.head()

                                               Weekly.rank  Peak.position  \
Artists             Name           Week
"Weird Al" Yankovic Canadian Idiot 2006-10-18           82           82.0
                                   2006-10-25           94           82.0
                                   2006-11-01           98           82.0
                    Word Crimes    2014-08-01           39           39.0
                                   2014-08-08           91           39.0

                                               Weeks.on.chart  \
Artists             Name           Week
"Weird Al" Yankovic Canadian Idiot 2006-10-18             1.0
                                   2006-10-25             2.0
                                   2006-11-01             3.0
                    Word Crimes    2014-08-01             1.0
                                   2014-08-08             2.0

                                                            Genre      DecDate
Artists             Name           Week
"Weird Al" Yankovic Canadian Idiot 2006-10-18  Comedy,Parody,Rock  2006.807692
                                   2006-10-25  Comedy,Parody,Rock  2006.826923
                                   2006-11-01  Comedy,Parody,Rock  2006.846154
                    Word Crimes    2014-08-01   Parody,Comedy,Pop  2014.576923
                                   2014-08-08   Parody,Comedy,Pop  2014.596154

In [142]:
last_artist = '"Weird Al" Yankovic'
last_song = "Canadian Idiot"
last_week = "2006-10-18"
last_rank = 82
jj = 1

for multindex, row in sorted_df2.iterrows():
        artists = multindex[0]
        song = multindex[1]
        week = multindex[2]
        todays_rank = row["Weekly.rank"]
        if last_rank == "":
            last_rank = todays_rank
            last_song = song
            last_week = week
            last_artist = artists
        if ((last_artist == artists) and (last_song == song)):

In [19]:
sorted_df2.head()

                                               Weekly.rank  Peak.position  \
Artists             Name           Week
"Weird Al" Yankovic Canadian Idiot 2006-10-18           82           82.0
                                   2006-10-25           94           82.0
                                   2006-11-01           98           82.0
                    Word Crimes    2014-08-01           39           39.0
                                   2014-08-08           91           39.0

                                               Weeks.on.chart  \
Artists             Name           Week
"Weird Al" Yankovic Canadian Idiot 2006-10-18             1.0
                                   2006-10-25             2.0
                                   2006-11-01             3.0
                    Word Crimes    2014-08-01             1.0
                                   2014-08-08             2.0

                                                            Genre      DecDate
Artists             Name           Week
"Weird Al" Yankovic Canadian Idiot 2006-10-18  Comedy,Parody,Rock  2006.807692
                                   2006-10-25  Comedy,Parody,Rock  2006.826923
                                   2006-11-01  Comedy,Parody,Rock  2006.846154
                    Word Crimes    2014-08-01   Parody,Comedy,Pop  2014.576923
                                   2014-08-08   Parody,Comedy,Pop  2014.596154

In [20]:
sorted_df2["Weekly.rank"].rolling(1).min()

Artists                 Name            Week
"Weird Al" Yankovic     Canadian Idiot  2006-10-18    82.0
                                        2006-10-25    94.0
                                        2006-11-01    98.0
                        Word Crimes     2014-08-01    39.0
                                        2014-08-08    91.0
                                                      ...
will.i.am, Nicki Minaj  Check It Out    2010-12-02    57.0
                                        2010-12-09    66.0
                                        2010-12-16    96.0
                                        2011-01-06    88.0
                                        2011-01-13    96.0
Name: Weekly.rank, Length: 97225, dtype: float64

In [21]:
sorted_df2["last_Rank"] = np.nan

In [22]:
sorted_df2.groupby(["Artists", "Name", "Week"]).mean()

                                                  Weekly.rank  Peak.position  \
Artists                Name           Week
"Weird Al" Yankovic    Canadian Idiot 2006-10-18         82.0           82.0
                                      2006-10-25         94.0           82.0
                                      2006-11-01         98.0           82.0
                       Word Crimes    2014-08-01         39.0           39.0
                                      2014-08-08         91.0           39.0
...                                                       ...            ...
will.i.am, Nicki Minaj Check It Out   2010-12-02         57.0           24.0
                                      2010-12-09         66.0           24.0
                                      2010-12-16         96.0           24.0
                                      2011-01-06         88.0           24.0
                                      2011-01-13         96.0           24.0

                                                  Weeks.on.chart      DecDate  \
Artists                Name           Week
"Weird Al" Yankovic    Canadian Idiot 2006-10-18             1.0  2006.807692
                                      2006-10-25             2.0  2006.826923
                                      2006-11-01             3.0  2006.846154
                       Word Crimes    2014-08-01             1.0  2014.576923
                                      2014-08-08             2.0  2014.596154
...                                                          ...          ...
will.i.am, Nicki Minaj Check It Out   2010-12-02            11.0  2010.923077
                                      2010-12-09            12.0  2010.942308
                                      2010-12-16            13.0  2010.961538
                                      2011-01-06            14.0  2011.019231
                                      2011-01-13            15.0  2011.038462

                                                  last_Rank
Artists                Name           Week
"Weird Al" Yankovic    Canadian Idiot 2006-10-18        NaN
                                      2006-10-25        NaN
                                      2006-11-01        NaN
                       Word Crimes    2014-08-01        NaN
                                      2014-08-08        NaN
...                                                     ...
will.i.am, Nicki Minaj Check It Out   2010-12-02        NaN
                                      2010-12-09        NaN
                                      2010-12-16        NaN
                                      2011-01-06        NaN
                                      2011-01-13        NaN

[97224 rows x 5 columns]

In [23]:
sorted_df3 = sorted_df2.groupby(["Artists", "Name", "Week"]).mean()

In [24]:
sorted_df5 = b_df2.sort_values(["Artists", "Name", "Week"])

In [25]:
for i, r in sorted_df5.iterrows():
    date_str = r["Week"]
    revised_date = dt.datetime.strptime(date_str, "%Y-%m-%d")
    week_date = dt.datetime.strftime(revised_date, "%Y-%W")

In [26]:
sorted_df5.head()

,Artists,Name,Weekly.rank,Peak.position,Weeks.on.chart,Week,Genre,DecDate
62365,"""Weird Al"" Yankovic",Canadian Idiot,82,82.0,1.0,2006-10-18,"Comedy,Parody,Rock",2006.807692
62281,"""Weird Al"" Yankovic",Canadian Idiot,94,82.0,2.0,2006-10-25,"Comedy,Parody,Rock",2006.826923
62189,"""Weird Al"" Yankovic",Canadian Idiot,98,82.0,3.0,2006-11-01,"Comedy,Parody,Rock",2006.846154
24590,"""Weird Al"" Yankovic",Word Crimes,39,39.0,1.0,2014-08-01,"Parody,Comedy,Pop",2014.576923
24543,"""Weird Al"" Yankovic",Word Crimes,91,39.0,2.0,2014-08-08,"Parody,Comedy,Pop",2014.596154

In [27]:
b_df3 = b_df2.sort_values(["Artists", "Name", "Weeks.on.chart"])

In [28]:
b_df4 = b_df3.reset_index()

In [29]:
b_df4.drop("index", axis=1, inplace=True)

In [30]:
b_df4.head()

,Artists,Name,Weekly.rank,Peak.position,Weeks.on.chart,Week,Genre,DecDate
0,"""Weird Al"" Yankovic",Canadian Idiot,82,82.0,1.0,2006-10-18,"Comedy,Parody,Rock",2006.807692
1,"""Weird Al"" Yankovic",Canadian Idiot,94,82.0,2.0,2006-10-25,"Comedy,Parody,Rock",2006.826923
2,"""Weird Al"" Yankovic",Canadian Idiot,98,82.0,3.0,2006-11-01,"Comedy,Parody,Rock",2006.846154
3,"""Weird Al"" Yankovic",Word Crimes,39,39.0,1.0,2014-08-01,"Parody,Comedy,Pop",2014.576923
4,"""Weird Al"" Yankovic",Word Crimes,91,39.0,2.0,2014-08-08,"Parody,Comedy,Pop",2014.596154

In [31]:
b_df4["LastWeek"] = np.nan

In [32]:
b_df4["nname"] = ""

In [33]:
for index, row in b_df4.iterrows():
    if row["Weeks.on.chart"] == 1.0:
        b_df4.loc[index, "LastWeek"] = 0
    else:
        last_week = index - 1
        lastVal = b_df4.loc[last_week, "Weekly.rank"]
        b_df4.loc[index, "LastWeek"] = lastVal

In [34]:
b_df4.head()

,Artists,Name,Weekly.rank,Peak.position,Weeks.on.chart,Week,Genre,DecDate,LastWeek,nname
0,"""Weird Al"" Yankovic",Canadian Idiot,82,82.0,1.0,2006-10-18,"Comedy,Parody,Rock",2006.807692,0.0,
1,"""Weird Al"" Yankovic",Canadian Idiot,94,82.0,2.0,2006-10-25,"Comedy,Parody,Rock",2006.826923,82.0,
2,"""Weird Al"" Yankovic",Canadian Idiot,98,82.0,3.0,2006-11-01,"Comedy,Parody,Rock",2006.846154,94.0,
3,"""Weird Al"" Yankovic",Word Crimes,39,39.0,1.0,2014-08-01,"Parody,Comedy,Pop",2014.576923,0.0,
4,"""Weird Al"" Yankovic",Word Crimes,91,39.0,2.0,2014-08-08,"Parody,Comedy,Pop",2014.596154,39.0,

In [35]:
for dex, row in b_df4.iterrows():
    song = row["Name"]
    art = row["Artists"]
    indicator = f"{art} - {song}"
    b_df4.loc[dex, "nname"] = indicator

In [36]:
b_df4.head()

,Artists,Name,Weekly.rank,Peak.position,Weeks.on.chart,Week,Genre,DecDate,LastWeek,nname
0,"""Weird Al"" Yankovic",Canadian Idiot,82,82.0,1.0,2006-10-18,"Comedy,Parody,Rock",2006.807692,0.0,"""Weird Al"" Yankovic - Canadian Idiot"
1,"""Weird Al"" Yankovic",Canadian Idiot,94,82.0,2.0,2006-10-25,"Comedy,Parody,Rock",2006.826923,82.0,"""Weird Al"" Yankovic - Canadian Idiot"
2,"""Weird Al"" Yankovic",Canadian Idiot,98,82.0,3.0,2006-11-01,"Comedy,Parody,Rock",2006.846154,94.0,"""Weird Al"" Yankovic - Canadian Idiot"
3,"""Weird Al"" Yankovic",Word Crimes,39,39.0,1.0,2014-08-01,"Parody,Comedy,Pop",2014.576923,0.0,"""Weird Al"" Yankovic - Word Crimes"
4,"""Weird Al"" Yankovic",Word Crimes,91,39.0,2.0,2014-08-08,"Parody,Comedy,Pop",2014.596154,39.0,"""Weird Al"" Yankovic - Word Crimes"

In [37]:
b_df4[b_df4["Week"] == "1999-07-19"].sort_values("Weekly.rank").head(15)

,Artists,Name,Weekly.rank,Peak.position,Weeks.on.chart,Week,Genre,DecDate,LastWeek,nname
22911,Destiny's Child,"Bills, Bills, Bills",2,1.0,6.0,1999-07-19,"R&;B,Rap",1999.557692,1.0,"Destiny's Child - Bills, Bills, Bills"
17246,Christina Aguilera,Genie In A Bottle,3,3.0,4.0,1999-07-19,"Dance-Pop,Pop",1999.557692,4.0,Christina Aguilera - Genie In A Bottle
70664,Pearl Jam,Last Kiss,4,2.0,9.0,1999-07-19,"Cover,Adult Alternative,Alternative Rock,Rock",1999.557692,3.0,Pearl Jam - Last Kiss
41326,Jennifer Lopez,If You Had My Love,5,1.0,11.0,1999-07-19,"Pop,R&;B",1999.557692,2.0,Jennifer Lopez - If You Had My Love
6611,Backstreet Boys,I Want It That Way,6,6.0,14.0,1999-07-19,"Rap,Boy Band,Pop",1999.557692,6.0,Backstreet Boys - I Want It That Way
74902,Ricky Martin,Livin' La Vida Loca,8,1.0,15.0,1999-07-19,"Pop,Latin Pop,Rock",1999.557692,5.0,Ricky Martin - Livin' La Vida Loca
80652,Smash Mouth,All Star,9,9.0,10.0,1999-07-19,"Punk Rock,Ska,Ska Punk,Screen,Pop-Rock,Soundtr...",1999.557692,10.0,Smash Mouth - All Star
1438,702,Where My Girls At?,10,4.0,13.0,1999-07-19,"Girl Group,R&;B",1999.557692,9.0,702 - Where My Girls At?
61056,Maxwell,Fortunate,11,4.0,16.0,1999-07-19,R&;B,1999.557692,11.0,Maxwell - Fortunate
1570,98 Degrees,The Hardest Thing,12,5.0,18.0,1999-07-19,"R&;B,Pop",1999.557692,12.0,98 Degrees - The Hardest Thing
82840,TLC,No Scrubs,13,1.0,23.0,1999-07-19,"Rap,Pop,R&;B",1999.557692,13.0,TLC - No Scrubs
80496,Sixpence None The Richer,Kiss Me,14,2.0,25.0,1999-07-19,"Adult Alternative,Adult Contemporary,Ballad,Po...",1999.557692,15.0,Sixpence None The Richer - Kiss Me
79406,Shania Twain,That Don't Impress Me Much,15,7.0,25.0,1999-07-19,"Pop-Rock,Pop,Country",1999.557692,17.0,Shania Twain - That Don't Impress Me Much
77799,Sarah McLachlan,I Will Remember You,16,16.0,30.0,1999-07-19,"Pop,Rock",1999.557692,18.0,Sarah McLachlan - I Will Remember You
9486,Blaque,808,18,8.0,15.0,1999-07-19,Rap,1999.557692,16.0,Blaque - 808

In [38]:
b_df4.dtypes

Artists            object
Name               object
Weekly.rank         int64
Peak.position     float64
Weeks.on.chart    float64
Week               object
Genre              object
DecDate           float64
LastWeek          float64
nname              object
dtype: object

In [39]:
for i, r in b_df4.iterrows():
    date_str = r["Week"]
    revised_date = dt.datetime.strptime(date_str, "%Y-%m-%d")
    b_df4.loc[i, "DT"] = revised_date

In [40]:
b_df4.head()

,Artists,Name,Weekly.rank,Peak.position,Weeks.on.chart,Week,Genre,DecDate,LastWeek,nname,DT
0,"""Weird Al"" Yankovic",Canadian Idiot,82,82.0,1.0,2006-10-18,"Comedy,Parody,Rock",2006.807692,0.0,"""Weird Al"" Yankovic - Canadian Idiot",2006-10-18
1,"""Weird Al"" Yankovic",Canadian Idiot,94,82.0,2.0,2006-10-25,"Comedy,Parody,Rock",2006.826923,82.0,"""Weird Al"" Yankovic - Canadian Idiot",2006-10-25
2,"""Weird Al"" Yankovic",Canadian Idiot,98,82.0,3.0,2006-11-01,"Comedy,Parody,Rock",2006.846154,94.0,"""Weird Al"" Yankovic - Canadian Idiot",2006-11-01
3,"""Weird Al"" Yankovic",Word Crimes,39,39.0,1.0,2014-08-01,"Parody,Comedy,Pop",2014.576923,0.0,"""Weird Al"" Yankovic - Word Crimes",2014-08-01
4,"""Weird Al"" Yankovic",Word Crimes,91,39.0,2.0,2014-08-08,"Parody,Comedy,Pop",2014.596154,39.0,"""Weird Al"" Yankovic - Word Crimes",2014-08-08

In [41]:
b_df4[b_df4["DT"] <= dt.datetime(2002,1,1)].sort_values(["Weekly.rank", "Week"], ascending=True).head(35)#.groupby("Weekly.rank").count()

,Artists,Name,Weekly.rank,Peak.position,Weeks.on.chart,Week,Genre,DecDate,LastWeek,nname,DT
22910,Destiny's Child,"Bills, Bills, Bills",1,1.0,5.0,1999-07-12,"R&;B,Rap",1999.538462,61.0,"Destiny's Child - Bills, Bills, Bills",1999-07-12
17247,Christina Aguilera,Genie In A Bottle,1,1.0,5.0,1999-07-26,"Dance-Pop,Pop",1999.576923,3.0,Christina Aguilera - Genie In A Bottle,1999-07-26
17248,Christina Aguilera,Genie In A Bottle,1,1.0,6.0,1999-08-02,"Dance-Pop,Pop",1999.596154,1.0,Christina Aguilera - Genie In A Bottle,1999-08-02
17249,Christina Aguilera,Genie In A Bottle,1,1.0,7.0,1999-08-09,"Dance-Pop,Pop",1999.615385,1.0,Christina Aguilera - Genie In A Bottle,1999-08-09
17250,Christina Aguilera,Genie In A Bottle,1,1.0,8.0,1999-08-16,"Dance-Pop,Pop",1999.634615,1.0,Christina Aguilera - Genie In A Bottle,1999-08-16
17251,Christina Aguilera,Genie In A Bottle,1,1.0,9.0,1999-08-23,"Dance-Pop,Pop",1999.653846,1.0,Christina Aguilera - Genie In A Bottle,1999-08-23
27851,Enrique Iglesias,Bailamos,1,1.0,9.0,1999-08-30,"En Espa\xc3\xb1ol,Pop",1999.673077,2.0,Enrique Iglesias - Bailamos,1999-08-30
27843,Enrique Iglesias,Bailamos,1,1.0,0.0,1999-09-06,"En Espa\xc3\xb1ol,Pop",1999.692308,100.0,Enrique Iglesias - Bailamos,1999-09-06
82846,TLC,Unpretty,1,1.0,3.0,1999-09-13,"R&;B,Rap",1999.711538,46.0,TLC - Unpretty,1999-09-13
82847,TLC,Unpretty,1,1.0,4.0,1999-09-20,"R&;B,Rap",1999.730769,1.0,TLC - Unpretty,1999-09-20
82849,TLC,Unpretty,1,1.0,5.0,1999-09-27,"R&;B,Rap",1999.750000,65.0,TLC - Unpretty,1999-09-27
58883,Mariah Carey,Heartbreaker,1,1.0,6.0,1999-10-04,"Rap,Dance-Pop,R&;B,Pop",1999.769231,16.0,Mariah Carey - Heartbreaker,1999-10-04
58884,Mariah Carey,Heartbreaker,1,1.0,7.0,1999-10-11,"Rap,Dance-Pop,R&;B,Pop",1999.788462,1.0,Mariah Carey - Heartbreaker,1999-10-11
77405,Santana,Smooth,1,1.0,3.0,1999-10-18,"Alternative Rock,Latin Pop,M\xc3\xa9xico,Latin...",1999.807692,1.0,Santana - Smooth,1999-10-18
77408,Santana,Smooth,1,1.0,4.0,1999-10-25,"Alternative Rock,Latin Pop,M\xc3\xa9xico,Latin...",1999.826923,1.0,Santana - Smooth,1999-10-25
77410,Santana,Smooth,1,1.0,5.0,1999-11-01,"Alternative Rock,Latin Pop,M\xc3\xa9xico,Latin...",1999.846154,26.0,Santana - Smooth,1999-11-01
77412,Santana,Smooth,1,1.0,6.0,1999-11-08,"Alternative Rock,Latin Pop,M\xc3\xa9xico,Latin...",1999.865385,11.0,Santana - Smooth,1999-11-08
77414,Santana,Smooth,1,1.0,7.0,1999-11-15,"Alternative Rock,Latin Pop,M\xc3\xa9xico,Latin...",1999.884615,8.0,Santana - Smooth,1999-11-15
77416,Santana,Smooth,1,1.0,8.0,1999-11-22,"Alternative Rock,Latin Pop,M\xc3\xa9xico,Latin...",1999.903846,6.0,Santana - Smooth,1999-11-22
77418,Santana,Smooth,1,1.0,9.0,1999-11-29,"Alternative Rock,Latin Pop,M\xc3\xa9xico,Latin...",1999.923077,7.0,Santana - Smooth,1999-11-29
77399,Santana,Smooth,1,1.0,0.0,1999-12-06,"Alternative Rock,Latin Pop,M\xc3\xa9xico,Latin...",1999.942308,47.0,Santana - Smooth,1999-12-06
77400,Santana,Smooth,1,1.0,1.0,1999-12-13,"Alternative Rock,Latin Pop,M\xc3\xa9xico,Latin...",1999.961538,0.0,Santana - Smooth,1999-12-13
77402,Santana,Smooth,1,1.0,2.0,1999-12-20,"Alternative Rock,Latin Pop,M\xc3\xa9xico,Latin...",1999.980769,78.0,Santana - Smooth,1999-12-20
77404,Santana,Smooth,1,1.0,3.0,1999-12-27,"Alternative Rock,Latin Pop,M\xc3\xa9xico,Latin...",2000.000000,73.0,Santana - Smooth,1999-12-27
77407,Santana,Smooth,1,1.0,4.0,2000-01-03,"Alternative Rock,Latin Pop,M\xc3\xa9xico,Latin...",2000.019231,70.0,Santana - Smooth,2000-01-03
17364,Christina Aguilera,What A Girl Wants,1,1.0,8.0,2000-01-10,"R&;B,Pop",2000.038462,11.0,Christina Aguilera - What A Girl Wants,2000-01-10
17365,Christina Aguilera,What A Girl Wants,1,1.0,9.0,2000-01-17,"R&;B,Pop",2000.057692,1.0,Christina Aguilera - What A Girl Wants,2000-01-17
77877,Savage Garden,I Knew I Loved You,1,1.0,5.0,2000-01-24,"Adult Contemporary,Australia,Ballad,Pop",2000.076923,31.0,Savage Garden - I Knew I Loved You,2000-01-24
77879,Savage Garden,I Knew I Loved You,1,1.0,6.0,2000-01-31,"Adult Contemporary,Australia,Ballad,Pop",2000.096154,20.0,Savage Garden - I Knew I Loved You,2000-01-31
77881,Savage Garden,I Knew I Loved You,1,1.0,7.0,2000-02-07,"Adult Contemporary,Australia,Ballad,Pop",2000.115385,13.0,Savage Garden - I Knew I Loved You,2000-02-07
59005,Mariah Carey,Thank God I Found You,1,1.0,1.0,2000-02-14,"R&;B,Pop",2000.134615,0.0,Mariah Carey - Thank God I Found You,2000-02-14
77884,Savage Garden,I Knew I Loved You,1,1.0,9.0,2000-02-21,"Adult Contemporary,Australia,Ballad,Pop",2000.153846,6.0,Savage Garden - I Knew I Loved You,2000-02-21
55905,Lonestar,Amazed,1,1.0,1.0,2000-02-28,"Pop,Country",2000.173077,0.0,Lonestar - Amazed,2000-02-28
55906,Lonestar,Amazed,1,1.0,2.0,2000-03-07,"Pop,Country",2000.192308,1.0,Lonestar - Amazed,2000-03-07
23053,Destiny's Child,Say My Name,1,1.0,3.0,2000-03-14,"Pop,R&;B",2000.211538,56.0,Destiny's Child - Say My Name,2000-03-14

In [98]:
b_df4.loc[27851, :]["Genre"].decode("utf-8", "ignore")#.replace("\xc3", "*")

AttributeError: 'str' object has no attribute 'decode'

In [99]:
import unicodedata

In [102]:
unicodedata.normalize("NFD", b_df4.loc[27851, :]["Genre"])

'En Espa\\xc3\\xb1ol,Pop'

In [104]:
b_df4.to_csv("hot100WithNewColumns.csv", encoding="utf-8")

In [42]:
b_df5 = b_df4.copy(deep=True)

In [43]:
b_df5.head()

,Artists,Name,Weekly.rank,Peak.position,Weeks.on.chart,Week,Genre,DecDate,LastWeek,nname,DT
0,"""Weird Al"" Yankovic",Canadian Idiot,82,82.0,1.0,2006-10-18,"Comedy,Parody,Rock",2006.807692,0.0,"""Weird Al"" Yankovic - Canadian Idiot",2006-10-18
1,"""Weird Al"" Yankovic",Canadian Idiot,94,82.0,2.0,2006-10-25,"Comedy,Parody,Rock",2006.826923,82.0,"""Weird Al"" Yankovic - Canadian Idiot",2006-10-25
2,"""Weird Al"" Yankovic",Canadian Idiot,98,82.0,3.0,2006-11-01,"Comedy,Parody,Rock",2006.846154,94.0,"""Weird Al"" Yankovic - Canadian Idiot",2006-11-01
3,"""Weird Al"" Yankovic",Word Crimes,39,39.0,1.0,2014-08-01,"Parody,Comedy,Pop",2014.576923,0.0,"""Weird Al"" Yankovic - Word Crimes",2014-08-01
4,"""Weird Al"" Yankovic",Word Crimes,91,39.0,2.0,2014-08-08,"Parody,Comedy,Pop",2014.596154,39.0,"""Weird Al"" Yankovic - Word Crimes",2014-08-08

In [44]:
def binningFunc(col):
    col = float(col)
    if col > 49:
        return 1
    elif col > 25:
        return 2
    elif col > 10:
        return 3
    elif col > 5:
        return 4
    elif col < 1:
        return 5
    else:
        return 6

In [45]:
b_df5 = b_df5.assign(bins = lambda x: x["Weekly.rank"].apply(binningFunc))

In [46]:
b_df5.head()

,Artists,Name,Weekly.rank,Peak.position,Weeks.on.chart,Week,Genre,DecDate,LastWeek,nname,DT,bins
0,"""Weird Al"" Yankovic",Canadian Idiot,82,82.0,1.0,2006-10-18,"Comedy,Parody,Rock",2006.807692,0.0,"""Weird Al"" Yankovic - Canadian Idiot",2006-10-18,1
1,"""Weird Al"" Yankovic",Canadian Idiot,94,82.0,2.0,2006-10-25,"Comedy,Parody,Rock",2006.826923,82.0,"""Weird Al"" Yankovic - Canadian Idiot",2006-10-25,1
2,"""Weird Al"" Yankovic",Canadian Idiot,98,82.0,3.0,2006-11-01,"Comedy,Parody,Rock",2006.846154,94.0,"""Weird Al"" Yankovic - Canadian Idiot",2006-11-01,1
3,"""Weird Al"" Yankovic",Word Crimes,39,39.0,1.0,2014-08-01,"Parody,Comedy,Pop",2014.576923,0.0,"""Weird Al"" Yankovic - Word Crimes",2014-08-01,2
4,"""Weird Al"" Yankovic",Word Crimes,91,39.0,2.0,2014-08-08,"Parody,Comedy,Pop",2014.596154,39.0,"""Weird Al"" Yankovic - Word Crimes",2014-08-08,1

In [47]:
def popularityPoints(column):
    if column == 1:
        return (abs(100 - column)+10)
    else:
        return abs(100 - column)

In [48]:
b_df5 = b_df5.assign(popPoints = lambda x: x["Weekly.rank"].apply(popularityPoints))

In [49]:
b_df5["POP"] = b_df5["bins"] * b_df5["popPoints"]

In [51]:
b_df5.to_csv("popularity.csv")